services:

  mongodb:
    image: mongo
    container_name: pokedex-db
    restart: always

    ports:
      - "27017:27017"

    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 123456

    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    container_name: pokedex-backend
    restart: always
    user: node

    ports:
      - "3000:3000"

    env_file:
      - ./backend/.env

    volumes:
      - ./backend/src:/app/src

    depends_on:
      - mongodb

  n8n:
    image: n8nio/n8n
    container_name: pokedex-n8n
    restart: always

    ports:
      - "5678:5678"

    volumes:
      - n8n-data:/home/node/.n8n

volumes:
  mongo-data:
  n8n-data: